### PR TITLE
[stable-v2.10] Revert "soc: intel_adsp: only implement FW_STATUS boot protocol for c…

### PR DESCRIPTION
**Pull request by kv2019i**
…avs"

This reverts commit fa798ce2d5be6deb8a3b0cde307a0a1dc5e88dde.

Link: https://github.com/thesofproject/sof/issues/9243

### CODE REVIEW

**Comment by kv2019i** [comment]
Backport to sof/stable-v2.10 branch.

**Comment by kv2019i** [comment]
E.g. needed for SOF 2.10 release to boot with linux-6.8 kernel.

**Review by andyross — APPROVED** [review]
Sure, but what's the process for getting a commit here upstreamed?  Seems like it should merge in Zephyr first and be backported, no?  Should I close the one I did so it doesn't get merged in the release rush and conflict?

**Review by lyakh — APPROVED** [review]

**Comment by kv2019i** [comment]
@andyross Let's have the patch go upstream normally in https://github.com/zephyrproject-rtos/zephyr/pull/74552 and then picked up to SOF main as usual. 

This stable-v2.10 is a special case as we are not (yet) aligned with release cadences of SOF and Zephyr, and e.g. now we are really close for final 2.10 release, so we have to do this as a hotfix (SOF2.10 has branched from SOF main a long time ago already, see https://github.com/thesofproject/sof/issues/9037 ). Here too normal policy is get to patches merged first upstream (and majority are), then backported, but exceptions are possible. Given this is a clean revert, this seems to be a prime candidate for an exception.

**Comment by marc-hb** [comment]
> (SOF2.10 has branched from SOF main a long time ago already, see https://github.com/thesofproject/sof/issues/9037 ).

That's only 2 weeks ago, it's not a "long time" ago. Has Zephyr become incompatible with SOF already? Zephyr is hardening it's 3.7 LTS release right now, it would be real pity not to use that for 2.10.

**Pull request merged**
